In [5]:
import numpy as np

var=np.array([1,2,3,4,5])

print(type(var))
print()
print("data type:",var.dtype)
print(var)

<class 'numpy.ndarray'>

data type: int32
[1 2 3 4 5]


In [6]:
import numpy as np

var=np.array([1.0,2.4,3.7,4,5])
print(var)
print("data type:",var.dtype)

[1.  2.4 3.7 4.  5. ]
data type: float64


In [7]:
import numpy as np

var=np.array(['s','u','f'])
print(var)
print("data type:",var.dtype)

['s' 'u' 'f']
data type: <U1


In [8]:
import numpy as np

var=np.array(['s','u','f',1,2,3.5])
print(var)
print("data type:",var.dtype)

['s' 'u' 'f' '1' '2' '3.5']
data type: <U32


In [11]:
x=np.array([1,2,3,4],dtype=np.int8)

print(x.dtype)
print(x)

int8
[1 2 3 4]


In [12]:
x=np.array([1,2,3,4],dtype='f')

print(x.dtype)
print(x)

float32
[1. 2. 3. 4.]


In [15]:
x2=np.array([1,2,3,4])
new=np.float32(x2)

print("x2:",x2.dtype)
print(x2)
print("new:",new.dtype)
print(new)

x2: int32
[1 2 3 4]
new: float32
[1. 2. 3. 4.]


In [16]:
x2=np.array([1,2,3,4])
new=np.float32(x2)

new_one=np.int_(new)
print(new_one)
print(new_one.dtype)

print("x2:",x2.dtype)
print(x2)
print("new:",new.dtype)
print(new)


[1 2 3 4]
int32
x2: int32
[1 2 3 4]
new: float32
[1. 2. 3. 4.]


In [19]:
x3=np.array([1,2,3,4])

NEW_1=x3.astype(float)
print(x3)
print(NEW_1)

[1 2 3 4]
[1. 2. 3. 4.]
