In [1]:
 pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [10]:
x=np.array([1,2,3,4,5])#list
print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
y=[1,2,3,4,5]
print(y)

print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [11]:
## time required

%timeit [i*4 for i in range(0,4)]

211 ns ± 6.33 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
import numpy as np

%timeit np.arange(1,9)**4

1.47 μs ± 47.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
print(np.arange(1,9))

[1 2 3 4 5 6 7 8]


In [ ]:
#######################        ARRAY              ################

In [18]:
import numpy as np

z=[1,2,3,4]
y=np.array(z)
print(y)
print(type(y))

print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [17]:
l=[]
for i in range(1,5):
    x=int(input("enter:"))
    l.append(x)
print(np.array(l))

enter: 150
enter: 160
enter: 123
enter: 156


[150 160 123 156]


In [ ]:
##################          Different types of Array             #################

In [19]:
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [22]:
arr3=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(arr3)

print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [24]:
arrn=np.array([1,2,3],ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10
