In [ ]:
##################               Zeros      ###############

In [10]:
import numpy as np

ar_zero=np.zeros(4)

arr=np.zeros((3,4))
print(ar_zero)
print()
print(arr)

print(arr.ndim)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [11]:
import numpy as np

jstone=np.ones(5)
ar_one=np.ones((4,4))

print(jstone)
print()
print(ar_one)

print(ar_one.ndim)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [ ]:
###############            EMPTY                  ###################

In [12]:
ar_em=np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


In [ ]:
#############     Range              ########

In [13]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [14]:
ar=np.arange(0,10,2)
print(ar)

[0 2 4 6 8]


In [ ]:
###########          Diagonal Matrix           ##############

In [15]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
###############         linspace           ###############

In [20]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [ ]:
##################          Random               ##############

In [21]:
import numpy as np

var=np.random.rand(4)
print(var)

[0.92265844 0.61325526 0.34700762 0.23786   ]


In [25]:
var2=np.random.randn(2)
print(var2)

[-0.85417633  1.17563127]


In [26]:
var3=np.random.ranf(3)
print(var3)

[0.56134263 0.58361379 0.2929694 ]


In [30]:
var4=np.random.randint(4,100)
print(var4)

80


In [31]:
var4=np.random.randint(4,100,10)
print(var4)

[17 75 10 12 55 87 46 25 88 48]
